In [ ]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForMaskedLM

tokenizer = AutoTokenizer.from_pretrained("klue/bert-base")
model = AutoModelForMaskedLM.from_pretrained("klue/bert-base")

Some weights of the model checkpoint at klue/bert-base were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
import torch
# 北 김정은 ""자주통일 새시대 열어나가야""(2보)
fake = "北 김정은 [MASK][MASK]자주통일 새시대 열어나가야[MASK][MASK][MASK]2보[MASK]"

fake_tokens = tokenizer.tokenize(fake)
fake_inputs = tokenizer.encode(fake, return_tensors="pt")

bert_outputs = model(fake_inputs)
bert_outputs = torch.argmax(bert_outputs['logits'], axis=-1)
print(bert_outputs)
bert_outputs = tokenizer.decode(bert_outputs[0], skip_special_tokens=True)
bert_outputs

tensor([[ 4362,   393,  3698,  1891,  2588, 24051,  4391,   121,  5986,  2112,
          3674,   100,  3697,  2420,  2120,    18]])


'일정 朴 대통령 한불 정상회의 참석 … 파리서 경제 · 문화외교.'

In [ ]:
import torch
# 서울에 다시 오존주의보 도심 서북 동북권 발령종합
fake = "서울에 [MASK] [MASK]주의보 도심 서북 동북권 발령종합"

fake_tokens = tokenizer.tokenize(fake)
fake_inputs = tokenizer.encode(fake, return_tensors="pt")

bert_outputs = model(fake_inputs)
bert_outputs = torch.argmax(bert_outputs['logits'], axis=-1)
print(bert_outputs)
bert_outputs = tokenizer.decode(bert_outputs[0], skip_special_tokens=True)
bert_outputs

tensor([[ 3671,  3671,  2170, 23382,  8031, 17939,  6246,   100,  7601,  2207,
         11180,    18,    18]])


'서울 서울에 초미세먼지 주의보 도심 · 동북권 발령..'

In [115]:
import pandas as pd
dataset = pd.read_csv("data/train.csv", encoding='cp949')
dataset.head()

ID                              text  target
0  ynat-v1_train_00000  정i :파1 미사z KT( 이용기간 2e 단] Q분종U2보       4
1  ynat-v1_train_00001       K찰.국DLwo 로L3한N% 회장 2 T0&}송=       3
2  ynat-v1_train_00002            m 김정) 자주통일 새,?r열1나가야1보       2
3  ynat-v1_train_00003     갤노트8 주말 27만대 개통…시장은 불법 보조금 얼룩       5
4  ynat-v1_train_00004      pI美대선I앞두고 R2fr단 발] $비해 감시 강화       6

In [24]:
for text, idx in zip(dataset.values, dataset.index):
    tokens = tokenizer.tokenize(text)
    if '[UNK]' in tokens:
        print(f"{idx}번째 문서 -> {tokens}")
        print(f'원본 : {text}')
        print('---------------------------------------------------------------------------------')

19번째 문서 -> ['페이스북', '인터넷', '드론', '[UNK]', '실물', '첫', '시험', '##비', '##행', '성공']
원본 : 페이스북 인터넷 드론 아퀼라 실물 첫 시험비행 성공
---------------------------------------------------------------------------------
48번째 문서 -> ['V', '##q', ')', 'Z', '!', '[UNK]', '자', '##o', '##구', '김정', '##R', '##e', '##트로', '##1', '$', '보', '##니', '##C', '.', '도', '##l', '##모', '##르', '"', '.', 'Q', '##k', '##이']
원본 : Vq)Z!\자o구 김정Re트로1$보니C.도l모르".Qk이
---------------------------------------------------------------------------------
67번째 문서 -> ['x', '##콩', '-', 'P', '##면', '##금', '[', 'T', '나', '%', '[UNK]', '…', 'g', '##트', '=', '물', '##J', '##1', '##h', '##나', '##고', '지', '>', '철', '%', '기고']
원본 : x콩-P면금[T 나%\…g트=물J1h나고 지>철 %기고
---------------------------------------------------------------------------------
87번째 문서 -> ['수능', '6', '?', "'", '{', '=', '"', '원', ')', '%', '&', 'G', '##울', '문', '##O', '##서', 'h', '##개', '##한', '[UNK]', '꽃', '##Z']
원본 : 수능 6?'{="원)%&G울 문O서 h개한 \꽃Z
---------------------------------------------

In [9]:
texts = ["SKT 부산 엑스포서 해양안전 통신기술 시연",
        "네이버 검색 광고 전체 광고 매출의 82.4% 차지",
        "美금융사 가상화폐 경계령…비자 CEO 거래처리 안할 것",
        "위클리 스A트<어린이날 국v과학관{행\ 다채",
        """O양정상회담$문q_l v8원에 모감주.무:";…yMq말은 번|"""]
for text in texts:
    print(tokenizer.tokenize(text))
    

['SKT', '부산', '엑스포', '##서', '해양', '##안전', '통신', '##기술', '시연']
['네이버', '검색', '광고', '전체', '광고', '매출', '##의', '82', '.', '4', '%', '차지']
['美', '금융', '##사', '가상', '##화', '##폐', '경계', '##령', '…', '비자', 'CEO', '거래처', '##리', '안', '##할', '것']
['위', '##클리', '스', '##A', '##트', '<', '어린이날', '국', '##v', '##과학', '##관', '{', '행', '[UNK]', '다채']
['O', '##양', '##정', '##상', '##회', '##담', '$', '문', '##q', '_', 'l', 'v', '##8', '##원', '##에', '모', '##감', '##주', '.', '무', ':', '"', ';', '…', 'y', '##M', '##q', '##말', '##은', '번', '|']


In [ ]:
from transformers import ElectraTokenizer, ElectraForMaskedLM
import torch

tokenizer = ElectraTokenizer.from_pretrained("google/electra-small-discriminator")
model = ElectraForMaskedLM.from_pretrained("google/electra-small-discriminator")

def clean_text(text):
    inputs = tokenizer(text, return_tensors="pt")
    with torch.no_grad():
        outputs = model(**inputs)
    
    logits = outputs.logits
    predicted_token_ids = torch.argmax(logits, dim=-1)
    
    cleaned_text = tokenizer.decode(predicted_token_ids[0])
    return cleaned_text

noisy_text = "Thsi is an exmaple of nosiy text."
cleaned_text = clean_text(noisy_text)
print(cleaned_text)


In [ ]:
import torch
from transformers import ElectraForPreTraining, ElectraTokenizer

discriminator = ElectraForPreTraining.from_pretrained("monologg/koelectra-base-v3-discriminator")
tokenizer = ElectraTokenizer.from_pretrained("monologg/koelectra-base-v3-discriminator")

In [45]:
sentence = "나는 방금 밥을 먹었다."
fake_sentence = "해외로밍 m금폭탄 n동차단 더 빨$진다"

fake_tokens = tokenizer.tokenize(fake_sentence)
fake_inputs = tokenizer.encode(fake_sentence, return_tensors="pt")

discriminator_outputs = discriminator(fake_inputs)
predictions = torch.round((torch.sign(discriminator_outputs[0]) + 1) / 2)


In [46]:
predictions[0][1:-1], fake_tokens

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        grad_fn=<SliceBackward0>),
 ['해외',
  '##로',
  '##밍',
  'm',
  '##금',
  '##폭탄',
  'n',
  '##동',
  '##차',
  '##단',
  '더',
  '빨',
  '$',
  '진다'])

# 데이터 클렌징

In [173]:
import re

def preprocess_and_mask_text(text):
    # 패턴 정의: 한글, 숫자, 한자, 공백만 남기고 나머지 제거
    pattern = re.compile(r'[^가-힣A-Z一-龯0-9 ]')
    
    # 마스크를 추가할 위치 확인 및 문자 제거
    preprocessed_text = []
    for char in text:
        if not pattern.match(char) or char == ' ':  # 유효한 문자(한글, 숫자, 한자)나 공백이면 그대로 유지
            preprocessed_text.append(char)
        else:  # 유효하지 않은 문자면
            if preprocessed_text and preprocessed_text[-1]=='[MASK]':
                continue
            preprocessed_text.append('[MASK]')

    # 최종 텍스트 결합
    final_text = ''.join(preprocessed_text)
    return final_text.strip()

# 테스트
text = "분당X'k gIdi}X'3·1 야ekK대^)t대립"
result = preprocess_and_mask_text(text)
print(result)

분당X[MASK] [MASK]I[MASK]X[MASK]3[MASK]1 야[MASK]K대[MASK]대립


In [196]:
import re

def preprocess_and_mask_text(text):
    # 패턴 정의: 한글, 숫자, 한자, 공백만 남기고 나머지 제거
    pattern = re.compile(r'[^가-힣A-Z一-龯0-9 ]')
    texts = text.split()
    # 마스크를 추가할 위치 확인 및 문자 제거
    preprocessed_text = []
    for text in texts:
        for char in text:
            if not pattern.match(char):
                continue
            preprocessed_text.append('[MASK]')
            break
        else:
            preprocessed_text.append(text)

    # 최종 텍스트 결합
    final_text = ' '.join(preprocessed_text)
    return final_text.strip()

# 테스트
text = "무선 장비로 침입자 막는다… KT텔레캅 새 보안 서비스종합"
result = preprocess_and_mask_text(text)
print(result)

무선 장비로 침입자 [MASK] KT텔레캅 새 보안 서비스종합


In [174]:
import pandas as pd
dataset = pd.read_csv("data/train.csv", encoding='cp949')

영어 소문자, 문장부호, 특수기호 모두 없애기

In [126]:
new_dataset = dataset.copy()
for idx, text in zip(dataset.index, dataset['text'].values):
    result = preprocess_text(text)
    new_dataset.loc[idx, 'text'] = result

In [175]:
masked_dataset = dataset.copy()
for idx, text in zip(dataset.index, dataset['text'].values):
    result = preprocess_and_mask_text(text)
    masked_dataset.loc[idx, 'text'] = result

In [177]:
masked_dataset

ID                                               text  \
0     ynat-v1_train_00000  정[MASK] [MASK]파1 미사[MASK] KT[MASK] 이용기간 2[MASK...   
1     ynat-v1_train_00001  K찰[MASK]국DL[MASK] 로L3한N[MASK] 회장 2 T0[MASK]송[M...   
2     ynat-v1_train_00002                [MASK] 김정[MASK] 자주통일 새[MASK]열1나가야1보   
3     ynat-v1_train_00003                 갤노트8 주말 27만대 개통[MASK]시장은 불법 보조금 얼룩   
4     ynat-v1_train_00004    [MASK]I美대선I앞두고 R2[MASK]단 발[MASK] [MASK]비해 감시 강화   
...                   ...                                                ...   
2795  ynat-v1_train_02795             트럼프 폭스뉴스 앵커들 충성도 점수매겨[MASK]10점만점에 12점도   
2796  ynat-v1_train_02796                        삼성 갤럭시S9 정식 출시 첫 주말 이통시장 잠잠   
2797  ynat-v1_train_02797  텔레그램[MASK]한D 등[MASK]亞서 2시간H다운[MASK]C버T정[MASK]3...   
2798  ynat-v1_train_02798               인터뷰 류현진 친구에게 안타 맞는 것 싫어해[MASK]승부는 냉정   
2799  ynat-v1_train_02799                               지능정보사회 대비 국가 종합대책 마련   

      target  
0          4  
1          3  
2          2  
3          5  
4          6  
...      ...  
2795       6  
2796       2  
2797       4  
2798       1  
2799       4  

[2800 rows x 3 columns]

In [180]:
masked_dataset.to_csv("./masked_train.csv", encoding='utf8')